spring.application.name=finance-tracker
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/finance_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Volamihaja1jos}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.tomcat.max-active=2