spring.application.name=finance-tracker

# 1. On définit l'URL (avec celle de Render en priorité, ou le local par défaut)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/finance_db}

# 2. IMPORTANT : On laisse vide ou absent les username/password si DATABASE_URL contient déjà les identifiants.
# Pour ton PC local, on peut passer par des variables ou configurer Hikari à part.
# Mais pour faire simple et compatible avec Render, utilise ceci :
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.tomcat.max-active=2