spring.application.name=finance-tracker

# Force le driver et le dialecte pour éviter que Hibernate cherche à les deviner avant la connexion
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuration de la source de données
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

# Gestion de la base de données
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Sécurité pour éviter les coupures Hikari en cours de route
spring.datasource.tomcat.max-active=2
spring.datasource.hikari.keepaliveTime=30000